//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_demoControls_TrackingPoint;
        
        private static SteamVR_Action_Boolean p_demoControls_MoveForward;
        
        private static SteamVR_Action_Boolean p_demoControls_MoveBackward;
        
        private static SteamVR_Action_Boolean p_demoControls_RotateLeft;
        
        private static SteamVR_Action_Boolean p_demoControls_RotateRight;
        
        private static SteamVR_Action_Vector2 p_demoControls_MoveJoystick;
        
        private static SteamVR_Action_Boolean p_demoControls_Record;
        
        private static SteamVR_Action_Boolean p_demoControls_PlayRecording;
        
        private static SteamVR_Action_Boolean p_demoControls_NextDialogue;
        
        public static SteamVR_Action_Pose demoControls_TrackingPoint
        {
            get
            {
                return SteamVR_Actions.p_demoControls_TrackingPoint.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean demoControls_MoveForward
        {
            get
            {
                return SteamVR_Actions.p_demoControls_MoveForward.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean demoControls_MoveBackward
        {
            get
            {
                return SteamVR_Actions.p_demoControls_MoveBackward.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean demoControls_RotateLeft
        {
            get
            {
                return SteamVR_Actions.p_demoControls_RotateLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean demoControls_RotateRight
        {
            get
            {
                return SteamVR_Actions.p_demoControls_RotateRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 demoControls_MoveJoystick
        {
            get
            {
                return SteamVR_Actions.p_demoControls_MoveJoystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean demoControls_Record
        {
            get
            {
                return SteamVR_Actions.p_demoControls_Record.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean demoControls_PlayRecording
        {
            get
            {
                return SteamVR_Actions.p_demoControls_PlayRecording.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean demoControls_NextDialogue
        {
            get
            {
                return SteamVR_Actions.p_demoControls_NextDialogue.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.demoControls_TrackingPoint,
                    SteamVR_Actions.demoControls_MoveForward,
                    SteamVR_Actions.demoControls_MoveBackward,
                    SteamVR_Actions.demoControls_RotateLeft,
                    SteamVR_Actions.demoControls_RotateRight,
                    SteamVR_Actions.demoControls_MoveJoystick,
                    SteamVR_Actions.demoControls_Record,
                    SteamVR_Actions.demoControls_PlayRecording,
                    SteamVR_Actions.demoControls_NextDialogue};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.demoControls_TrackingPoint,
                    SteamVR_Actions.demoControls_MoveForward,
                    SteamVR_Actions.demoControls_MoveBackward,
                    SteamVR_Actions.demoControls_RotateLeft,
                    SteamVR_Actions.demoControls_RotateRight,
                    SteamVR_Actions.demoControls_MoveJoystick,
                    SteamVR_Actions.demoControls_Record,
                    SteamVR_Actions.demoControls_PlayRecording,
                    SteamVR_Actions.demoControls_NextDialogue};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.demoControls_TrackingPoint};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.demoControls_MoveForward,
                    SteamVR_Actions.demoControls_MoveBackward,
                    SteamVR_Actions.demoControls_RotateLeft,
                    SteamVR_Actions.demoControls_RotateRight,
                    SteamVR_Actions.demoControls_Record,
                    SteamVR_Actions.demoControls_PlayRecording,
                    SteamVR_Actions.demoControls_NextDialogue};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.demoControls_MoveJoystick};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.demoControls_MoveForward,
                    SteamVR_Actions.demoControls_MoveBackward,
                    SteamVR_Actions.demoControls_RotateLeft,
                    SteamVR_Actions.demoControls_RotateRight,
                    SteamVR_Actions.demoControls_MoveJoystick,
                    SteamVR_Actions.demoControls_Record,
                    SteamVR_Actions.demoControls_PlayRecording,
                    SteamVR_Actions.demoControls_NextDialogue};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_demoControls_TrackingPoint = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/DemoControls/in/TrackingPoint")));
            SteamVR_Actions.p_demoControls_MoveForward = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DemoControls/in/MoveForward")));
            SteamVR_Actions.p_demoControls_MoveBackward = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DemoControls/in/MoveBackward")));
            SteamVR_Actions.p_demoControls_RotateLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DemoControls/in/RotateLeft")));
            SteamVR_Actions.p_demoControls_RotateRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DemoControls/in/RotateRight")));
            SteamVR_Actions.p_demoControls_MoveJoystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/DemoControls/in/MoveJoystick")));
            SteamVR_Actions.p_demoControls_Record = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DemoControls/in/Record")));
            SteamVR_Actions.p_demoControls_PlayRecording = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DemoControls/in/PlayRecording")));
            SteamVR_Actions.p_demoControls_NextDialogue = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DemoControls/in/NextDialogue")));
        }
    }
}
