//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_DemoControls p_DemoControls;
        
        public static SteamVR_Input_ActionSet_DemoControls DemoControls
        {
            get
            {
                return SteamVR_Actions.p_DemoControls.GetCopy<SteamVR_Input_ActionSet_DemoControls>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_DemoControls = ((SteamVR_Input_ActionSet_DemoControls)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_DemoControls>("/actions/DemoControls")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.DemoControls};
        }
    }
}
