//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_DemoControls : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose TrackingPoint
        {
            get
            {
                return SteamVR_Actions.demoControls_TrackingPoint;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveForward
        {
            get
            {
                return SteamVR_Actions.demoControls_MoveForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveBackward
        {
            get
            {
                return SteamVR_Actions.demoControls_MoveBackward;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateLeft
        {
            get
            {
                return SteamVR_Actions.demoControls_RotateLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateRight
        {
            get
            {
                return SteamVR_Actions.demoControls_RotateRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.demoControls_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Record
        {
            get
            {
                return SteamVR_Actions.demoControls_Record;
            }
        }
    }
}
